core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('voucher.urls')),
    # path('process/',include('process.urls')),
    path('accounts/',include('accounts.urls')),
    path('acknowledgement/',include('acknowledgement.urls')),
    path('approval/',include('approval.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

admin.site.index_title = 'Payment Voucher Management'

voucher/urls.py
import imp
from unicodedata import name
from django import views
from django.urls import path
from .import views

urlpatterns = [
    path('',views.search,name='search'),
    path('request/voucher/',views.requestclient,name='requestclient'),
    path('request/voucher/save',views.requestclient_save,name='requestclient_save'),
    # path('success_page/',views.success_page,name='success_page'),
    path('voucher/<int:voucher_id>/update/',views.update_voucher,name='update'),
    path('voucher/update/save/',views.update_voucher_save,name='update_voucher_save'),

    path('voucher/<int:voucher_id>/delete/',views.delete_voucher,name='delete_voucher'),

    path('total_approved/',views.total_approved,name='total_approved'),
    path('pending_approved/',views.pending_approved,name='pending_approved'),
    path('disapproved/',views.disapproved,name='disapproved'),


    path('central_page/',views.central_page,name='central_page'),
    path('upload-file/',views.bulk_upload_member,name='bulk_upload_member'),
    # path('acknowlegement/<int:acknowlege_id>/disapproved',views.disapprove_acknowlege,name='disapprove_acknowlege'),

    path('acknowlegement/',views.acknowlege,name='acknowlege'),
    path('acknowlegement/<int:acknowlege_id>/approved',views.approve_acknowlege,name='approve_acknowlege'),
    path('acknowlegement/<int:acknowlege_id>/disapproved',views.disapprove_acknowlege,name='disapprove_acknowlege'),

    path('acknowlegement/manager/',views.manager_page,name='manager_page'),
    path('manager/<int:manager_id>/approved',views.approved_manager,name='approved_manager'),
    path('manager/<int:manager_id>/disapproved',views.disapproved_manager,name='disapproved_manager'),

    # pdf 
    path('print_approved/<int:voucher_id>/',views.print_approved,name='print_approved'),

    path('testing_page/',views.testing_page,name='testing_page'),
    path('testing_save/',views.testing_save,name='testing_save'),

]

acknowledgement/models.py
from ast import Return
from re import A
from django.db import models

from accounts.models import Client, User
from approval.models import Approve


class Acknlowledge(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    
    acknlowledged_by = models.IntegerField(default=0)

    def __str__(self) :
        return str(self.user.email)

    class Meta:        
        verbose_name = 'Acknlowledge'
        verbose_name_plural = 'Acknlowledges'   

class Demo(models.Model):
    client = models.ForeignKey(Client, on_delete=models.DO_NOTHING)
    description = models.TextField()
    acknowlege_by = models.ForeignKey(Acknlowledge,on_delete=models.DO_NOTHING)
    approved_by = models.ForeignKey(Approve,on_delete=models.DO_NOTHING)
    def __str__(self):
        return self.id

    class Meta:
    
       
        verbose_name = 'Demo'
        verbose_name_plural = 'Demos'        

voucher/models.py
from django.db import models
from accounts.models import Client, User
import random

from approval.models import Approve
from .utils import client_uid
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw


class PaymentRequisitionVoucher(models.Model):
    client              = models.ForeignKey(Client,on_delete=models.DO_NOTHING)
    tracking_id         = models.CharField(max_length=20,default=client_uid(),editable=False)
    payee               = models.CharField(max_length=250)
    account_number      = models.CharField(max_length=250)

    qty                 = models.CharField(max_length=250)
    rate                = models.CharField(max_length=250)
    details             = models.CharField(max_length=250)
    amount              = models.CharField(max_length=250)

    qty_2                 = models.CharField(max_length=250,blank=True,null=True)
    rate_2                = models.CharField(max_length=250,blank=True,null=True)
    details_2             = models.CharField(max_length=250,blank=True,null=True)
    amount_2              = models.CharField(max_length=250,blank=True,null=True)

    qty_3                 = models.CharField(max_length=250,blank=True,null=True)
    rate_3                = models.CharField(max_length=250,blank=True,null=True)
    details_3             = models.CharField(max_length=250,blank=True,null=True)
    amount_3              = models.CharField(max_length=250,blank=True,null=True)

    qty_4                 = models.CharField(max_length=250,blank=True,null=True)
    rate_4                = models.CharField(max_length=250,blank=True,null=True)
    details_4             = models.CharField(max_length=250,blank=True,null=True)
    amount_4             = models.CharField(max_length=250,blank=True,null=True)

    qty_5                 = models.CharField(max_length=250,blank=True,null=True)
    rate_5                = models.CharField(max_length=250,blank=True,null=True)
    details_5             = models.CharField(max_length=250,blank=True,null=True)
    amount_5             = models.CharField(max_length=250,blank=True,null=True)

    total               = models.CharField(max_length=250)
    amount_in_words     = models.CharField(max_length=250)
    requested_by        = models.CharField(max_length=250)
    acknowledge_by      = models.IntegerField(default=0)
    approved_by         = models.IntegerField(default=0)
    voucher_created_at  = models.DateTimeField(auto_now_add=True)
    voucher_updated_at  = models.DateField(auto_now=True)

    acknowlege_email = models.EmailField(blank=True,null=True)
    approve_email = models.EmailField(blank=True,null=True)

    is_deleted = models.BooleanField(default=False)
    def __str__(self):
        return f'{self.tracking_id} - {self.requested_by}'

    class Meta:        
        verbose_name = 'Payment Requisition Voucher'
        verbose_name_plural = 'Payment Requisition Vouchers'
        ordering = ('-voucher_updated_at',)

    """ 
    Generating Tracking ID for each Voucher
    """    
    # def save(self, *args,**kw):
    #     tracking_id_list = [x for x in range(10)]
    #     tracking_items = ['NBL']

    #     for i in range(6):
    #         num = random.choice(tracking_id_list)
    #         tracking_items.append(num)

    #     tracking_string = "".join(str(item) for item in tracking_items)    
    #     self.tracking_id = tracking_string
        
    #     super(PaymentRequisitionVoucher,self).save(*args,**kw)


class PaymentVerification(models.Model):
    payvoucher = models.ForeignKey(PaymentRequisitionVoucher, on_delete=models.CASCADE,blank=True,null=True)
    name = models.CharField(max_length=200,blank=True,null=True)
    qr_code = models.ImageField(upload_to='qr_codes',blank=True)

    def __str__(self):
        return f'{self.id} - {self.payvoucher.tracking_id}'

    def save(self, *args, **kwargs):
        qrcode_img = qrcode.make(self.name)    
        canvas = Image.new('RGB', (290,290), 'white')
        draw = ImageDraw.Draw(canvas)
        canvas.paste(qrcode_img)
        fname = f'qr_code-{self.name}.png'
        buffer = BytesIO()
        canvas.save(buffer, 'PNG')
        self.qr_code.save(fname,File(buffer), save=False)
        canvas.close()
        super().save(*args, **kwargs)


class UploadMember(models.Model):
    
    file_name                   = models.FileField(upload_to='membercreation')
    activated                     = models.BooleanField(default=False)
    created_at                    = models.DateField(auto_now_add=True)
    updated_at                    = models.DateField(auto_now=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = ("Bulk Creation")
        verbose_name_plural = ("Bulk Creations")    


class Tested(models.Model):
    user = models.OneToOneField(User,on_delete=models.PROTECT)
    approved_by = models.ForeignKey(Approve,on_delete=models.PROTECT)
    acknownlege_by = models.ForeignKey(User,on_delete=models.PROTECT,related_name='acknowlege')
    mtext = models.TextField()

    def __str__(self):
        return self.id

voucher/forms.py
from django import forms
from .models import PaymentRequisitionVoucher, Tested, UploadMember
# from django.utils.translation import gettext_lazy as _


# form bulk creations of member
class UploadMemberForm(forms.ModelForm):
    class Meta:
        model = UploadMember
        fields = ("file_name",)

class PaymentRequisitionForm(forms.ModelForm):
    
    class Meta:
        model = PaymentRequisitionVoucher
        fields = '__all__'
        exclude = 'tracking_id','acknowledge_by','approved_by',


class UpdatePaymentRequisitionForm(forms.ModelForm):
    class Meta:
        model = PaymentRequisitionVoucher
        fields = '__all__'
        exclude = 'acknowledge_by','approved_by',
        # widgets = {
        #     'client':forms.TextInput(attrs={
        #         'type':'hidden',
        #     }),
            
        # }    

class TestingForm(forms.ModelForm):
    class Meta:
        model = Tested
        fields ='__all__'
        exclude = ('user',)

templates/voucher/acknowlege.html
{% extends "shared/layout.html" %}


{% block body %} 
<div class="table">
            <table class="table" style="border-spacing: 45px;">
                <tr>
                    <th>#</th>
                    <th>Client Email</th>
                    <th>Date Created</th>
                    <th>Tracking ID</th>                    
                    <th>Status</th>
                    <th>Print</th>
    
    
                </tr>
                
                {% for voucher in vouchers %}
                <tr>
                    
                    <td>
                        {{ forloop.counter }}
                    </td>
                    <td>
                        {{ voucher.client.user.email }}
                    </td>

                    <td>
                        {{voucher.voucher_created_at }}
                    </td>
                    <td>
                        {{ voucher.tracking_id }}
                    </td>
                    
                    <td>
                        {% if voucher.acknowledge_by == 0 %}
                        <a href="{% url 'approve_acknowlege' acknowlege_id=voucher.id %}" class="btn btn-success"  >Approve </a>
                        <a href="{% url 'disapprove_acknowlege' acknowlege_id=voucher.id %}" class="btn btn-success"  >Disapproved </a>
                        {% elif  voucher.acknowledge_by == 1 %}
                        <button class="btn btn-warning" disabled="disabled" data-toggle="modal" data-target="#reply_modal" >Approved </button>
                        {% else %}
                        <button class="btn btn-danger" disabled="disabled"  data-toggle="modal" data-target="#reply_modal" >Disapprove </button>
                        {% endif %}</td>
                    </td>
                    <td>
                        <a href="{% url 'print_approved' voucher.id %}">Print</a> 
                    </td>
                </tr>
                {% endfor %}
    
           </table>

           {% endblock body %}            

templates/voucher/central_admin.html
{% extends "shared/layout.html" %}


{% block body %} 
<div class="header">
    <div>
        <ul>
            <li>
                <a href="{% url 'register' %}">Add member</a>
            </li>
            <li>

            </li>
        </ul>
    </div>
</div>

<h2>
    All USERS
</h2>

        
         <!-- For bulk creations of member /  -->
    <form  method="POST" action="{% url 'bulk_upload_member' %}" enctype="multipart/form-data">
        {% csrf_token %}
        
        
        <div >
            {{ form.label  }}
          {{ form | safe }}
        </div>
        <button type="submit" class="btn btn-primary">Upload</button>
  </form>

 

{% endblock body %}            

templates/voucher/delete_voucher.html
{% extends "shared/layout.html" %}
{% load static %}

{% block body %}
<form method='POST'>
    {% csrf_token %}
    <p>
        Are you sure you wanna delete this 
        <button type="submit" value="Delete">Delete</button>
    </p>
</form>
{% endblock body %}

templates/voucher/email_approve_admin_text.html
{% autoescape off %}
{% load static %}

   <h2>
      
    Hi,{{ voucher.client.user.email }}
   </h2>

    <p style="color: green;">
        Hi {{ voucher.payee }}, You now finally been Approve with <b>TRACKING ID: {{ voucher.tracking_id }}</b>, you can now print the voucher now
    Please click this link to print this Voucher 

    http://{{domain}}{% url 'dashboard' %}
    </p>
{% endautoescape %}

templates/voucher/email_approve_text.html
{% autoescape off %}
{% load static %}

   <h2>
       
    Hi,{{ approve_email }}
   </h2>

    <p style="color: red;">
        {{ voucher.requested_by }}  request for your Approval
    with the following details below:    
    </p>
    <h3>
        Voucher Created at {{ voucher.voucher_created_at }}
    </h3>
    <div class="headings">
        <h2>
            Payment Requisiton Voucher         
        </h2>
        
    </div>
   
    <div class="account-details">
        <div>
            <label for="id_payee">Payee:</label>
            {{ voucher.payee }}
            <div>
                <span>Tracking ID: {{ voucher.tracking_id }} </span>
            </div>
        </div>

        <div>
            <label for="id_account_number"  id="account_number">Account number</label>
           
            <div>
                {{ voucher.account_number }}
            </div>
            <span> </span>
            
        </div>
    </div>
<hr>

    <table>
        <tbody>
            <tr>
               
                    
                <th>
                    Qty
                </th>
                <th>
                    Details
                </th>
                <th>
                    Rate
                </th>
                <th>
                    Amount
                </th>
            
            
            </tr>
        </tbody>

        <tr>
            
                <td class="qty">
                
                    {{ voucher.qty }}
                    {{ voucher.qty_2 }}
                    {{ voucher.qty_3 }}
                    {{ voucher.qty_4 }}
                    {{ voucher.qty_5 }}
                   
                    
                    
                </td>

                <td class="details">
                    {{ voucher.details }}
                    {{ voucher.details_2 }}
                    {{ voucher.details_3 }}
                    {{ voucher.details_4 }}
                    {{ voucher.details_5 }}
                   
                </td>

               
                    <td class="rate">
                        <div class="format">
                            {{ voucher.rate }}
                            {{ voucher.rate_2 }}
                            {{ voucher.rate_3 }}
                            {{ voucher.rate_4 }}
                            {{ voucher.rate_5 }}
                            
                        <label for="id_total">
                            Total:
                        </label>
                        </div>
                    </td>
    
                    <td class="amount">
                        <div class="format">
                            {{ voucher.amount }}
                            {{ voucher.amount_2 }}
                            {{ voucher.amount_3 }}
                            {{ voucher.amount_4 }}
                            {{ voucher.amount_5 }}             
                            {{ voucher.total }} 
                       
                        </div>
                    </td>
               
            
        </tr>
    </table>

    <div class="words">
        <label for="id_amount_in_words">Amount in words:</label>
       {{ voucher.amount_in_words }}
    </div>
    
    <div class="verification">
        <div class="request_by">
            <label for="id_requested_by">Requested By:</label>
            {{ voucher.requested_by }}
            
        </div>
      
        
    </div>

    <div>
        Please click this link to acknowlege this Voucher 

    http://{{domain}}{% url 'acknowlege' %}
    </div>
{% endautoescape %}

templates/voucher/email_disapprove_admin_text.html
{% autoescape off %}
{% load static %}

   <h2>
      
    Hi,{{ voucher.client.user.email }}
   </h2>

    <p style="color: red;">
        Hi {{ voucher.requested_by }}, You now finally been Disapprove with <b>TRACKING ID: {{ voucher.tracking_id }}</b>, keep in contact with the Manager
    
    </p>
{% endautoescape %}

templates/voucher/email_text.html
{% autoescape off %}
{% load static %}

   <h2>
      
    Hi,{{ acknowlege_email }}
   </h2>

    <p style="color: red;">
        {{ voucher.requested_by }}  request for your Acknowlegement
    with the following details below:    
    </p>

    <div class="headings">
        <h2>
            Payment Requisiton Voucher         
        </h2>
        
    </div>
   
    <div class="account-details">
        <div>
            <label for="id_payee">Payee:</label>
            {{ voucher.payee }}
            <div>
                <span>Tracking ID: {{ voucher.tracking_id }} </span>
            </div>
        </div>

        <div>
            <label for="id_account_number"  id="account_number">Account number</label>
           
            <div>
                {{ voucher.account_number }}
            </div>
            <span> </span>
            
        </div>
    </div>
<hr>

    <table>
        <tbody>
            <tr>
               
                    
                <th>
                    Qty
                </th>
                <th>
                    Details
                </th>
                <th>
                    Rate
                </th>
                <th>
                    Amount
                </th>
            
            
            </tr>
        </tbody>

        <tr>
            
                <td class="qty">
                
                    {{ voucher.qty }}
                    {{ voucher.qty_2 }}
                    {{ voucher.qty_3 }}
                    {{ voucher.qty_4 }}
                    {{ voucher.qty_5 }}
                   
                    
                    
                </td>

                <td class="details">
                    {{ voucher.details }}
                    {{ voucher.details_2 }}
                    {{ voucher.details_3 }}
                    {{ voucher.details_4 }}
                    {{ voucher.details_5 }}
                   
                </td>

               
                    <td class="rate">
                        <div class="format">
                            {{ voucher.rate }}
                            {{ voucher.rate_2 }}
                            {{ voucher.rate_3 }}
                            {{ voucher.rate_4 }}
                            {{ voucher.rate_5 }}
                            
                        <label for="id_total">
                            Total:
                        </label>
                        </div>
                    </td>
    
                    <td class="amount">
                        <div class="format">
                            {{ voucher.amount }}
                            {{ voucher.amount_2 }}
                            {{ voucher.amount_3 }}
                            {{ voucher.amount_4 }}
                            {{ voucher.amount_5 }}             
                            {{ voucher.total }} 
                       
                        </div>
                    </td>
               
            
        </tr>
    </table>

    <div class="words">
        <label for="id_amount_in_words">Amount in words:</label>
       {{ voucher.amount_in_words }}
    </div>
    
    <div class="verification">
        <div class="request_by">
            <label for="id_requested_by">Requested By:</label>
            {{ voucher.requested_by }}
            
        </div>
      
        
    </div>

    <div>
        Please click this link to acknowlege this Voucher 

    http://{{domain}}{% url 'acknowlege' %}
    </div>

{% endautoescape %}

templates/voucher/requestvouccher.html
{% extends "shared/layout.html" %}
{% load static %}

{% block body %}

<form action="{% url 'requestclient_save' %}" method="POST" id="form">
    {% csrf_token %}
   
    <div class="headings">
        <h2>
            Payment Requisiton Voucher         
        </h2>
        
    </div>
   
    <div class="account-details">
        <div>
            <label for="id_payee">Payee</label>
            <input type="text" name="payee" required>
            <span>Tracking ID: </span>
        </div>

        <div>
            <label for="id_account_number"  id="account_number">Account number</label>
            <input type="text" name="account_number" required>
            <span> </span>
            
        </div>
    </div>


    <table>
        <tbody>
            <tr>
               
                    
                <th>
                    Qty
                </th>
                <th>
                    Details
                </th>
                <th>
                    Rate
                </th>
                <th>
                    Amount
                </th>
            
            
            </tr>
        </tbody>

        <tr>
            
                <td class="qty">
                    <input type="text" name="qty" id="qty1" required>
                    <input type="text" name="qty_2" id="qty2">
                    <input type="text" name="qty_3" id="qty3">
                    <input type="text" name="qty_4" id="qty4">
                    <input type="text" name="qty_5" id="qty5">
                    
                    
                </td>

                <td class="details">
                    <input type="text" name="details" required>
                    <input type="text" name="details_2">
                    <input type="text" name="details_3">
                    <input type="text" name="details_4">
                    <input type="text" name="details_5">
                   
                </td>

               
                    <td class="rate">
                        <div class="format">
                            <input type="text" name="rate" id="rate1" required>
                            <input type="text" name="rate_2" id="rate2">
                            <input type="text" name="rate_3" id="rate3">
                            <input type="text" name="rate_4" id="rate4">
                            <input type="text" name="rate_5" id="rate5">
                       
                        <label for="id_total">
                            Total
                        </label>
                        </div>
                    </td>
    
                    <td class="amount">
                        <div class="format">
                            <input type="text" name="amount" id="amount1" required>
                            <input type="text" name="amount_2" id="amount2">
                            <input type="text" name="amount_3" id="amount3">
                            <input type="text" name="amount_4" id="amount4">
                            <input type="text" name="amount_5" id="amount5">
                            <input type="number" name="total" id="total">                         
                       
                        </div>
                    </td>
               
            
        </tr>
    </table>

    <div class="words">
        <label for="id_amount_in_words">Amount in words</label>
        <input type="text" name="amount_in_words" id="amount_in_words" required>
    </div>
    
    <div class="verification">
        <div class="request_by">
            <input type="text" name="requested_by" required>
            <label for="id_requested_by">Requested By</label>
        </div>
        
        <div class="request_by">
            <select name="acknowlege_email" id="acknowledge_by">
                <option value="">select email</option>
                {% for s in user_obj %}
                  <option value="{{ s.email }}">{{ s.email }}</option>
                {% endfor %}
            </select>
            <label for="id_acknowlege_by">Acknowlege By</label>
        </div>
    
        <div class="request_by">
            
            <select name="approve_email" id="approved_by" required>
                <option>Select email</option>
                {% for mail in user_obj %}
                  <option value="{{ mail.email }}">
                    {{ mail.email }}
                  </option>
                {% endfor %}
            </select>
            <label for="id_approved_by">Approve By</label>
        </div>
        
    </div>

    
    <!-- <div>
            
    </div> -->
    <button type="submit">submit</button>
</form>


<!-- FORM PREVIEW BEFORE SUBMISSION  -->


{% endblock body %}

{% block script %}
{% static 'js/request.js' %}

{% endblock script %}  

templates/voucher/search.html
{% extends "shared/layout.html" %}

{% block body %}
    <h2>
        Search Using Tracking ID
    </h2>

    <form action="{% url 'search' %}" method="GET">
        <label for="id_search"> SEARCH</label>
        <input type="text" name="keyword" id="search" placeholder="search here...">

        <button type="submit" class="btn btn-default" method="GET" value="search">
            <!-- <i class="fas fa-search"></i> -->
            search
          </button>
    </form>

    <div>
        <p>
            {{ data }}
        </p>
    </div>    
{% endblock body %}

templates/voucher/success_page.html
{% extends "shared/layout.html" %}

{% block body %}

<h4>
    Form submitted successfully use this <b>TRACKING ID : {{ voucher.tracking_id }}</b> to check back later
</h4>
{% endblock body %}

templates/voucher/update_voucher.html
{% extends "shared/layout.html" %}
{% load static %}

{% block body %}

<form action="{% url 'update_voucher_save' %}" method="POST" id="form">
    {% csrf_token %}
   
    <div class="headings">
        <h2>
            Update Payment Requisiton Voucher         
        </h2>
        
    </div>
   
    <div class="account-details">
        <div>
            <label for="id_payee">Payee</label>
            <input type="text" name="payee" value="{{ voucher.payee }}">
            <span>Tracking ID:{{ voucher.tracking_id }} </span>
        </div>

        <div>
            <label for="id_account_number"  id="account_number">Account number</label>
            <input type="text" name="account_number" value="{{ voucher.account_number }}">
            <span> </span>
            
        </div>
    </div>


    <table>
        <tbody>
            <tr>
               
                    
                <th>
                    Qty
                </th>
                <th>
                    Details
                </th>
                <th>
                    Rate
                </th>
                <th>
                    Amount
                </th>
            
            
            </tr>
        </tbody>

        <tr>
            
                <td class="qty">
                    <input type="text" name="qty" id="qty1" value="{{ voucher.qty }}">
                    <input type="text" name="qty_2" id="qty2" value="{{ voucher.qty_2 }}">
                    <input type="text" name="qty_3" id="qty3" value="{{ voucher.qty_3 }}">
                    <input type="text" name="qty_4" id="qty4"  value="{{ voucher.qty_4 }}">
                    <input type="text" name="qty_5" id="qty5"  value="{{ voucher.qty_5 }}">
                    
                    
                </td>

                <td class="details">
                    <input type="text" name="details" value="{{ voucher.details }}">
                    <input type="text" name="details_2" value="{{ voucher.details_2 }}">
                    <input type="text" name="details_3" value="{{ voucher.details_3 }}">
                    <input type="text" name="details_4" value="{{ voucher.details_4 }}">
                    <input type="text" name="details_5" value="{{ voucher.details_5 }}">
                   
                </td>

               
                    <td class="rate">
                        <div class="format">
                            <input type="text" name="rate" id="rate1" value="{{ voucher.rate }}">
                            <input type="text" name="rate_2" id="rate2" value="{{ voucher.rate_2 }}">
                            <input type="text" name="rate_3" id="rate3" value="{{ voucher.rate_3 }}">
                            <input type="text" name="rate_4" id="rate4" value="{{ voucher.rate_4 }}">
                            <input type="text" name="rate_5" id="rate5" value="{{ voucher.rate_5 }}">
                       
                        <label for="id_total">
                            Total
                        </label>
                        </div>
                    </td>
    
                    <td class="amount">
                        <div class="format">
                            <input type="text" name="amount" id="amount1" value="{{ voucher.amount }}">
                            <input type="text" name="amount_2" id="amount2" value="{{ voucher.amount_2 }}">
                            <input type="text" name="amount_3" id="amount3" value="{{ voucher.amount_3 }}">
                            <input type="text" name="amount_4" id="amount4"value="{{ voucher.amount_4 }}">
                            <input type="text" name="amount_5" id="amount5" value="{{ voucher.amount_5 }}">
                            <input type="number" name="total" id="total" value="{{ voucher.total }}" >                         
                       
                        </div>
                    </td>
               
            
        </tr>
    </table>

    <div class="words">
        <label for="id_amount_in_words">Amount in words</label>
        <input type="text" name="amount_in_words" id="amount_in_words" value="{{ voucher.amount_in_words }}">
    </div>
    
    <div class="verification">
        <div class="request_by">
            <input type="text" name="requested_by" value="{{ voucher.requested_by }}">
            <label for="id_requested_by">Requested By</label>
        </div>
        
        <div class="request_by">
            <input type="text" name="acknowlege_email" value="{{ voucher.acknowlege_email }}">            
            <label for="id_acknowlege_by">Acknowlege By</label>
        </div>
    
        <div class="request_by">            
           <input type="text" name="approve_email" value="{{ voucher.approve_email }}">
            <label for="id_approved_by">Approve By</label>
        </div>
        
    </div>
    <input type="hidden" name="client" value="{{ voucher.client.user.email }}">
    <input type="hidden" name="voucher_id" value="{{ voucher.id }}">
   
    
    <button type="submit">update</button>
</form>


<div>
    <img src={{ payverify.qr_code.url }} alt="qr_code">
</div>

<!-- FORM PREVIEW BEFORE SUBMISSION  -->


{% endblock body %}

{% block script %}
{% static 'js/request.js' %}

{% endblock script %}  